//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenemeSWE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shelf
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string book_id { get; set; }
        public string photo { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string language { get; set; }
        public string subject { get; set; }
        public string category { get; set; }
        public string release_date { get; set; }
        public string reading_link { get; set; }
        public Nullable<double> scrollPostion { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual User User { get; set; }
    }
}
